# Generated by Django 5.2 on 2025-04-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_project_github_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='fa_icon',
            field=models.CharField(),
        ),
    ]
