# Generated by Django 5.2 on 2025-04-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='fa_icon',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
